<?php

return [
    'patterns' => [
        'whois' => [
            'registrar whois server:',
            'whois:',
            'refer:'
        ],
        'availability' => [
            '% no entries found.*',
            '% no match.*',
            '% no such domain',
            '% not registered.*',
            '% nothing found',
            '%% no entries found.*',
            '%error: no entries found',
            '%error:101: no entries found',
            '%error:103: domain is not registered',
            '.* - no match',
            '.* is free',
            '.*: no entries found.*',
            '.*domain not found.*',
            '.*no match for.*',
            '.*this domain name has not been registered.*',
            '>>> domain .* is available for registration',
            '\*\*\* nothing found for this query.*',
            'available',
            'data not found.*',
            'domain .* has been reserved.*',
            'domain .* is available.*',
            'domain .* not found.*',
            'domain status: free',
            'domain status: no object found',
            'domain unknown',
            'el dominio no se encuentra registrado.*',
            'invalid query or domain name not known.*',
            'nincs talalat \/ no match',
            'no data found.*',
            'no entries found for the selected source.*',
            'no entries found.*',
            'no found.*',
            'no information available about domain name.*',
            'no information was found.*',
            'no match.*',
            'no object found.*',
            'no such domain.*',
            'no_se_encontro_el_objeto\/object_not_found',
            'not find matchingrecord',
            'not found.*',
            'not registered.*',
            'nothing found.*',
            'object does not exist.*',
            'query_status: 220 available',
            'registration status: available',
            'reserved by.*',
            'sorry, but domain: .*, not found in database',
            'status:.*available',
            'status:.*free',
            'the domain .* was not found.*',
            'the domain has not been registered.*',
            'the queried object does not exist.*',
            'the requested domain was not found.*',
            'this domain name has not been registered.*'
        ]
    ],
];
